# Generated by Django 4.0.3 on 2022-03-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_band_hometown'),
        ('listings', '0006_band_like_new_band_record_company'),
    ]

    operations = [
    ]
